version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4
jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

      - codecov/upload:
          file: ./target/site/jacoco/jacoco.xml

  docs:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: OpenJDK-PPA
          command: sudo add-apt-repository ppa:openjdk-r/ppa
      - run:
          name: Update APT
          command: sudo apt-get update
      - run:
          name: OpenJDK-Install
          command: sudo apt-get install openjdk-11-jdk-headless -y
      - run:
          name: Build the docs with javadoc
          command: javadoc -d docs src/main/java/fr/univavignon/pokedex/api/*
      - persist_to_workspace:
          root: .
          paths: docs

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config --global user.email "hicham.anb84@gmail.com"
            git config --global user.name "hicham-anbari"
      - add_ssh_keys:
          fingerprints:
            - "10:81:d5:4d:c0:be:6c:5b:58:d7:24:bd:c0:42:7c:fc"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dist docs

workflows:
  sample:
    jobs:
      - build-and-test
      - docs-deploy:
        jobs:
          requires:
            - build-and-test
            - docs
          filters:
            branches:
              only: master