version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean install
      - run:
          name: Test
          command: mvn test
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./target/site/jacoco/jacoco.xml

workflows:
  sample:
    jobs:
      - build-and-test:
        filters:
          branches:
            only: master
