version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn clean install
      - run:
          name: Test
          command: mvn test

workflows:
  sample:
    jobs:
      - build-and-test:
        filters:
          branches:
            only: master
